image:
  repository: local
  version: latest
imagePullSecrets:
  - name: regcred

app:
  protocol: http
  domain: techofmany.com
  cmd: ["npm", "run", "start", "-w", "site"]
  port: 3001
  replicas: 1
  revisionHistoryLimit: 1
