apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-{{ .Values.projectName }}-admin
  labels:
    app: {{ .Values.projectName }}
    tier: admin
spec:
  replicas: {{ .Values.admin.replicas }}
  revisionHistoryLimit: {{ .Values.admin.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.projectName }}
      tier: admin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}
        tier: admin
    spec:
      containers:
      - name: k8s-{{ .Values.projectName }}-admin
        image: "{{ .Values.image.repository }}/{{ .Values.projectName }}:{{ .Values.image.version }}"
        command: ["npm", "run", "start", "-w", "admin"]
        imagePullPolicy: IfNotPresent
        env:
        - name: ROOT_URL
          value: "{{ .Values.admin.protocol }}://{{ .Values.admin.domain }}"
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-auth-secret
              key: USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-auth-secret
              key: PASSWORD
        - name: TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: token-secret
              key: TOKEN
        ports:
        - containerPort: {{ .Values.admin.port }}
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
