apiVersion: v1
kind: Service
metadata:
  name: k8s-{{ .Values.projectName }}-admin
spec:
  type: NodePort
  selector:
    app: {{ .Values.projectName }}
    tier: admin
  ports:
  - protocol: TCP
    port: {{ .Values.admin.port }}
    targetPort: {{ .Values.admin.port }}
