apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
    tier: admin
  ports:
  - protocol: TCP
    port: {{ .Values.admin.port }}
    targetPort: {{ .Values.admin.port }}
