apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume-claim
  labels:
    app: tools
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.volumeSize }}
