apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-{{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    tier: public
spec:
  replicas: {{ .Values.public.replicas }}
  revisionHistoryLimit: {{ .Values.public.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: public
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: public
    spec:
      containers:
      - name: k8s-{{ .Release.Name }}
        image: {{ .Values.image.repository }}/{{ .Release.Name }}:{{ .Values.image.version }}
        command: ["npm", "run", "start", "-w", "site"]
        imagePullPolicy: IfNotPresent
        env:
        - name: ROOT_URL
          value: "{{ .Values.public.protocol }}://{{ .Values.public.domain }}"
        - name: {{ .Values.database.auth.userEnv }}
          valueFrom:
            secretKeyRef:
              name: db-auth-secret
              key: USERNAME
        - name: {{ .Values.database.auth.passEnv }}
          valueFrom:
            secretKeyRef:
              name: db-auth-secret
              key: PASSWORD
        - name: TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: TOKEN
        ports:
        - name: entry
          containerPort: {{ .Values.public.port }}
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---

apiVersion: v1
kind: Service
metadata:
  name: k8s-{{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
    tier: public
  ports:
  - protocol: TCP
    port: {{ .Values.public.port }}
    targetPort: entry
