image:
  repository: local
  version: latest
imagePullSecrets:
  - name: regcred

public:
  protocol: http
  domain: techofmany.com
  port: 3001
  replicas: 1
  revisionHistoryLimit: 1

admin:
  protocol: http
  domain: admin.techofmany.com
  port: 4001
  replicas: 1
  revisionHistoryLimit: 1

database:
  image: mongo:latest
  volumeSize: 10Gi
  port: 27017
  auth:
    userEnv: MONGO_INITDB_ROOT_USERNAME
    passEnv: MONGO_INITDB_ROOT_PASSWORD
