apiVersion: v1
kind: Secret
metadata:
  name: "db-auth-secret"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "db-auth-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $username := (get $secretData "USERNAME") | default (randAlphaNum 10 | b64enc) }}
  USERNAME: {{ $username | quote }}
  {{- $password := (get $secretData "PASSWORD") | default (randAlphaNum 32 | b64enc) }}
  PASSWORD: {{ $password | quote }}
