apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}
    tier: database
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: database
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: database
    spec:
      containers:
      - name: {{ .Release.Name }}-db
        image: {{ .Values.database.image }}
        imagePullPolicy: IfNotPresent
        args:
          - --bind_ip
          - 0.0.0.0
        env:
        - name: {{ .Values.database.auth.userEnv }}
          valueFrom:
            secretKeyRef:
              name: db-auth-secret
              key: USERNAME
        - name: {{ .Values.database.auth.passEnv }}
          valueFrom:
            secretKeyRef:
              name: db-auth-secret
              key: PASSWORD
        ports:
        - containerPort: {{ .Values.database.port }}
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
        volumeMounts:
          - name: {{ .Release.Name }}-db-storage
            mountPath: /data/db
      volumes:
      - name: {{ .Release.Name }}-db-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-db-claim
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
