apiVersion: v1
kind: Service
metadata:
  name: k8s-database
spec:
  ports:
  - port: {{ .Values.database.port }}
    targetPort: {{ .Values.database.port }}
  selector:
    app: tools
    tier: database
