apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-{{ .Values.projectName }}
  labels:
    app: {{ .Values.projectName }}
    tier: public
spec:
  replicas: {{ .Values.public.replicas }}
  revisionHistoryLimit: {{ .Values.public.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.projectName }}
      tier: public
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}
        tier: public
    spec:
      containers:
      - name: k8s-{{ .Values.projectName }}
        image: {{ .Values.image.repository }}/{{ .Values.projectName }}:{{ .Values.image.version }}
        command: ["npm", "run", "start", "-w", "site"]
        imagePullPolicy: IfNotPresent
        env:
        - name: ROOT_URL
          value: "{{ .Values.public.protocol }}://{{ .Values.public.domain }}"
        - name: {{ .Values.database.auth.userEnv }}
          valueFrom:
            secretKeyRef:
              name: db-auth-secret
              key: USERNAME
        - name: {{ .Values.database.auth.passEnv }}
          valueFrom:
            secretKeyRef:
              name: db-auth-secret
              key: PASSWORD
        - name: TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: token-secret
              key: TOKEN
        ports:
        - containerPort: {{ .Values.public.port }}
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
