apiVersion: v1
kind: Service
metadata:
  name: k8s-{{ .Values.projectName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.projectName }}
    tier: public
  ports:
  - protocol: TCP
    port: {{ .Values.public.port }}
    targetPort: {{ .Values.public.port }}
