apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-public
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
    tier: public
  ports:
  - protocol: TCP
    port: {{ .Values.public.port }}
    targetPort: {{ .Values.public.port }}
